#region COPYRIGHT
//
//     THIS IS GENERATED BY TEMPLATE
//     
//     AUTHOR  :     ROYE
//     DATE       :     2010
//
//     COPYRIGHT (C) 2010, TIANXIAHOTEL TECHNOLOGIES CO., LTD. ALL RIGHTS RESERVED.
//
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace System.Office.Excel
{
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = true)]
    public class ToCellAttribute : Attribute
    {
        private string _CellAddress;
        public string CellAddress
        {
            get { return _CellAddress; }
        }

        public ToCellAttribute(string cellAddress)
        {
            _CellAddress = cellAddress;
        }

    }
}
