#region COPYRIGHT
//
//     THIS IS GENERATED BY TEMPLATE
//     
//     AUTHOR  :     ROYE
//     DATE       :     2010
//
//     COPYRIGHT (C) 2010, TIANXIAHOTEL TECHNOLOGIES CO., LTD. ALL RIGHTS RESERVED.
//
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace System.Office.Excel
{
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = true)]
    public class ToDynamicRangeAttribute : Attribute
    {
        public ToDynamicRangeAttribute(int startRow, string startColumnName, string endColumnName)
        {
            StartRow = startRow;
            StartColumnName = startColumnName;
            EndColumnName = endColumnName;
        }

        public int StartRow { get; set; }
        public string StartColumnName { get; set; }
        public string EndColumnName { get; set; }
    }
}
