#region COPYRIGHT
//
//     THIS IS GENERATED BY TEMPLATE
//     
//     AUTHOR  :     ROYE
//     DATE       :     2010
//
//     COPYRIGHT (C) 2010, TIANXIAHOTEL TECHNOLOGIES CO., LTD. ALL RIGHTS RESERVED.
//
#endregion

using System;
using System.ComponentModel;

namespace System.Threading
{
    [Browsable(true), TypeConverter(typeof(ExpandableObjectConverter))]
    public interface ILockable
    {
        bool TryAquireLock();

        void AquireLock();

        void ReleaseLock();

        bool Locked { get; }
    }
}
