#region COPYRIGHT
//
//     THIS IS GENERATED BY TEMPLATE
//     
//     AUTHOR  :     ROYE
//     DATE       :     2010
//
//     COPYRIGHT (C) 2010, TIANXIAHOTEL TECHNOLOGIES CO., LTD. ALL RIGHTS RESERVED.
//
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace TX.Framework.WindowUI.Controls
{
    public delegate void SubItemEndEditingEventHandler(object sender, SubItemEndEditingEventArgs e);

    public class SubItemEndEditingEventArgs : SubItemEventArgs
    {
        private string _DisplayText;
        private bool _cancel;

        public SubItemEndEditingEventArgs(ListViewItem item, int subItemIndex, string displayText, bool cancel)
            : base(item, subItemIndex)
        {
            DisplayText = displayText;
            Cancel = cancel;
        }

        public string DisplayText { get; set; }

        public bool Cancel { get; set; }
    }
}
