#region COPYRIGHT
//
//     THIS IS GENERATED BY TEMPLATE
//     
//     AUTHOR  :     ROYE
//     DATE       :     2010
//
//     COPYRIGHT (C) 2010, TIANXIAHOTEL TECHNOLOGIES CO., LTD. ALL RIGHTS RESERVED.
//
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace TX.Framework.WindowUI.Controls
{
    public delegate void SubItemEventHandler(object sender, SubItemEventArgs e);
    
    public class SubItemEventArgs : EventArgs
    {
        private int _SubItemIndex = -1;
        private ListViewItem _Item = null;

        public SubItemEventArgs(ListViewItem item, int subItemIndex)
        {
            _SubItemIndex = subItemIndex;
            _Item = item;
        }

        /// <summary>
        /// 子项的索引值
        /// </summary>
        public int SubItemIndex
        {
            get { return _SubItemIndex; }
        }

        /// <summary>
        /// ListView控件的项
        /// </summary>
        public ListViewItem Item
        {
            get { return _Item; }
        }
    }
}
