#region COPYRIGHT
//
//     THIS IS GENERATED BY TEMPLATE
//     
//     AUTHOR  :     ROYE
//     DATE       :     2010
//
//     COPYRIGHT (C) 2010, TIANXIAHOTEL TECHNOLOGIES CO., LTD. ALL RIGHTS RESERVED.
//
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace TX.Framework.WindowUI.Controls
{
    public class SelectedTreeListViewItemCollection : ListView.SelectedListViewItemCollection
    {
        public SelectedTreeListViewItemCollection(TreeListView TreeListView)
            : base((ListView)TreeListView)
        {
        }

        public bool Contains(TreeListViewItem item)
        {
            return base.Contains((ListViewItem)item);
        }

        public int IndexOf(TreeListViewItem item)
        {
            return base.IndexOf((ListViewItem)item);
        }

        public new TreeListViewItem this[int index]
        {
            get { return (TreeListViewItem)base[index]; }
        }
    }
}
