#region COPYRIGHT
//
//     THIS IS GENERATED BY TEMPLATE
//     
//     AUTHOR  :     ROYE
//     DATE       :     2010
//
//     COPYRIGHT (C) 2010, TIANXIAHOTEL TECHNOLOGIES CO., LTD. ALL RIGHTS RESERVED.
//
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TX.Framework.WindowUI.Controls
{
    /// <summary>
    /// Expand / Collapse method
    /// </summary>
    [Serializable]
    public enum TreeListViewExpandMethod
    {
        /// <summary>
        /// Expand when double clicking on the icon
        /// </summary>
        IconDbleClick,
        /// <summary>
        /// Expand when double clicking on the entire item
        /// </summary>
        EntireItemDbleClick,
        /// <summary>
        /// Expand when double clicking on the item only
        /// </summary>
        ItemOnlyDbleClick,
        /// <summary>
        /// None
        /// </summary>
        None
    }
}
