#region COPYRIGHT
//
//     THIS IS GENERATED BY TEMPLATE
//     
//     AUTHOR  :     ROYE
//     DATE       :     2010
//
//     COPYRIGHT (C) 2010, TIANXIAHOTEL TECHNOLOGIES CO., LTD. ALL RIGHTS RESERVED.
//
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TX.Framework.WindowUI.Controls
{
    [Serializable]
    public enum TreeListViewAction
    {
        /// <summary>
        /// By Keyboard
        /// </summary>
        ByKeyboard,
        /// <summary>
        /// ByMouse
        /// </summary>
        ByMouse,
        /// <summary>
        /// Collapse
        /// </summary>
        Collapse,
        /// <summary>
        /// Expand
        /// </summary>
        Expand,
        /// <summary>
        /// Unknown
        /// </summary>
        Unknown
    }
}
