#region COPYRIGHT
//
//     THIS IS GENERATED BY TEMPLATE
//     
//     AUTHOR  :     ROYE
//     DATE       :     2010
//
//     COPYRIGHT (C) 2010, TIANXIAHOTEL TECHNOLOGIES CO., LTD. ALL RIGHTS RESERVED.
//
#endregion

using System;
using System.Collections.Generic;
using System.Text;

namespace System.Text.Template
{
    public enum TemplateTokenType
    {
        Expression,
        Statement,
        ForEach,
        EndBlock,
        Set,
        While,
        If,
        Else,
        ElseIf,
        Include,
        Render,
        MacroBegin,
        MacroEnd
    }
}
